remote_theme: just-the-docs/just-the-docs@v0.3.3

# Enable or disable heading anchors
heading_anchors: true

# Colour scheme
color_scheme: "nakapan"

# Aux links for the upper right navigation
aux_links:
  "Jenkins test on GitHub":
    - "//github.com/jernejp21/Jenkins_test/tree/gh-pages"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2022 Jernej Pangerc"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
