remote_theme: just-the-docs/just-the-docs

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Jenkins test on GitHub":
    - "//github.com/jernejp21/Jenkins_test/tree/gh-pages"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
