name: 🪲 Report a bug
description: Create a bug report to help improve Marlin Firmware
title: "[BUG] (bug summary)"
body:
  - type: markdown
    attributes:
      value: |
        # Bug Details

  - type: textarea
    attributes:
      label: Bug Description
      description: >-
        Describe the bug in this section. Tell us what you were trying to do and what
        happened that you did not expect. Provide a clear and concise description of the
        problem and include as many details as possible.

        When pasting formatted text don't forget to put ` ``` ` (on its own line) before and after to make it readable.
      placeholder: |
        Marlin doesn't work.
    validations:
      required: true

  - type: input
    attributes:
      label: Bug Timeline
      description: Is this a new bug or an old issue? When did it first start?

  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        What did you expect to happen?
      placeholder: I expected it to move left.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened instead?
      placeholder: It moved right instead of left.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >-
        Please describe the steps needed to reproduce the issue.
      placeholder: |
        1. [First Step] ...
        2. [Second Step] ...
        3. [and so on] ...
    validations:
      required: true

    - type: markdown
    attributes:
      value: |
        # Attachments

  - type: markdown
    attributes:
      value: |
        ### Optional items to include:
        - 'Log output from the host. (`M111 S247` for maximum logging.)'
        - Images or videos demonstrating the problem, if it helps to make it clear.
        - A G-Code file that exposes the problem, if not affecting _all_ G-code.

  - type: textarea
    attributes:
      label: Additional information & file uploads
      description: >-
        If you've made any other modifications to the firmware, please describe them in detail.

        When pasting formatted text don't forget to put ` ``` ` (on its own line) before and after to make it readable.
