name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install GCC
      run: sudo apt-get install gcc-arm-non-eabi
    - name: Make
      run: |
        pwd             # /home/runner/work/try/try
        cd STM32L476/Debug
        pwd             # /home/runner/work/try/try/hello
        make clean
        make all
    - name: make clean
      run: |
        make clean
    - name: make all
      run: |
        make all
