name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Experiment
      run: |
        pwd             # /home/runner/work/try/try
        mkdir hello
        cd hello
        pwd             # /home/runner/work/try/try/hello
