name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install GCC
      run: sudo apt-get install gcc-arm-none-eabi
    - name: Make
      run: |
        cd STM32L476/Debug
        pwd
        make clean
        make all
