name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: working directory
      working-directory: STM32L476/Debug
      run: echo "$pwd"
    - name: make clean
      run: make clean
    - name: make all
      run: make all
