- name: Release with Changelog
  # You may pin to the exact commit or the version.
  # uses: fregante/release-with-changelog@304ef3a41972f031ea67fa705ed37a811f37d1b1
  uses: fregante/release-with-changelog@v3.5.1
  with:
    # Specific tag to generate changelog against
    tag: # optional
    # Personal access token (PAT) used to create releases
    token: 
    # Custom title for the release
    title: # optional
    # Regex to exclude commits based on their title (don't include the initial and final `/`)
    exclude: # optional, default is 
    # Markdown template to be included in release notes
    template: # optional, default is {commits}

{range}

    # Markdown template for each commit entry in release notes
    commit-template: # optional, default is - {hash} {title}
    # Format of git date included in commit-template
    date-format: # optional, default is short
    # Specify if you want get changelog in reverse order
    sort: # optional, default is desc
    # Set to true if you want to have draft release
    draft: # optional, default is false
    # Set to true if you want to have prerelease instead release
    prerelease: # optional, default is false
    # Set to true to skip creating a release when all commits are excluded
    skip-on-empty: # optional, default is false
